"""modify course

Revision ID: c82ee37935c9
Revises: db9b0434d4dd
Create Date: 2025-02-06 16:51:28.252283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c82ee37935c9'
down_revision: Union[str, None] = 'db9b0434d4dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_prerequisite',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'prerequisite_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_prerequisite')
    # ### end Alembic commands ###
