"""add indexes

Revision ID: cdec2f7a959e
Revises: 8afc7adb6559
Create Date: 2025-02-06 19:20:33.482270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdec2f7a959e'
down_revision: Union[str, None] = '8afc7adb6559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_course_prerequisite_course_id', 'course_prerequisite', ['course_id'], unique=False)
    op.create_index('ix_course_prerequisite_prerequisite_id', 'course_prerequisite', ['prerequisite_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_course_prerequisite_prerequisite_id', table_name='course_prerequisite')
    op.drop_index('ix_course_prerequisite_course_id', table_name='course_prerequisite')
    # ### end Alembic commands ###
